namespace: petclinic

petclinic:
  image: "springcommunity/spring-petclinic"
  tag: "2.7.0"
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8080

mssql:
  image: "mcr.microsoft.com/mssql/server"
  tag: "2022-latest"
  saPassword: "YourStrong!Passw0rd"
  database: "PetClinicDB"
  service:
    type: ClusterIP
    port: 1433
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1"

ingress:
  enabled: false
  host: petclinic.local
  annotations: {}
