namespace: petclinic

petclinic:
  image: springcommunity/spring-petclinic:3.2.0
  replicas: 1

sqlserver:
  image: mcr.microsoft.com/mssql/server:2022-latest
  database: petclinic
  saPassword: ChangeMeStrong!

otel:
  serviceName: petclinic
  otlpEndpoint: http://splunk-otel-collector:4317

splunk:
  realm: us1
  accessToken: CHANGEME
